---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

FORMATTERS_DISABLE_ERRORS: false

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE
  - PYTHON
  - EDITORCONFIG
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_GIT_DIFF

  # Conflicting with Prettier
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  
  # Disabled due to false positives
  - MARKDOWN_MARKDOWN_LINK_CHECK

  # Disabled due to unneeded linting. Checkov, Kics and Trivy are sufficient.
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN

  # Disable due to poor configuration options
  - ACTION_ACTIONLINT

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

# Use yml file to allow the use of comments. Megalinter's default is .markdown-lint.json
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdown-lint.yml

YAML_V8R_FILTER_REGEX_EXCLUDE: "dependabot.yml" # Dependabot yaml in SchemaStore is currently not up to date. Dependabot is validated on push by GitHub by default.
